/**:
  ros__parameters:
    preprocess:
      # 2 is better in the Kimera-Multi dataset
      lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
      scan_line: 64
      timestamp_unit: 3                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
      blind: 0.8

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.003
      b_gyr_cov: 0.001
      fov_degree:    360.0
      det_range:     80.0
      extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
      extrinsic_T: [ 4.20405650e-02, -7.38194508e-02, -1.59149569e-01 ]
      extrinsic_R: [-9.4869700000e-04, 9.9999500000e-01, 2.9021900000e-03,
                  -1.8558300000e-04, 2.9020100000e-03, -9.9999600000e-01,
                  -1.0000000000e+00, -9.4923200000e-04, 1.8282900000e-04]

    filter_size_map: 0.3 # bigger voxel size

    publish:
      path_en:  true
      scan_publish_en:  true       # false: close all the point cloud output
      dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
      scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

    pcd_save:
      pcd_save_en: false
      interval: -1                 # how many LiDAR frames saved in each pcd file;
                                   # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
