/**:
  ros__parameters:
    common:
      lid_topic:  "/acl_jackal2/lidar_points"
  #    imu_topic:  "/acl_jackal2/imu/data"
      imu_topic:  "/acl_jackal2/forward/imu"
      time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
      map_frame: "map"

    preprocess:
      lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
      scan_line: 16
      scan_rate: 10                # only need to be set for velodyne, unit: Hz,
      timestamp_unit: 2            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
      blind: 2

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.003
      b_gyr_cov: 0.001
      fov_degree:    360.0
      det_range:     100.0
      extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
  #    extrinsic_T: [ 0.13, 0, 0.52]
  #    extrinsic_R: [ 1, 0, 0,
  #                   0, 1, 0,
  #                   0, 0, 1]

      extrinsic_T: [ 0.0410363, -0.109472, -0.0644936 ]
      extrinsic_R: [ -0.0265678, -0.99964361, -0.00260855,
                     -0.06280272, 0.00427343, -0.99801681,
                     0.99767228, -0.02635129, -0.06289387 ]

    filter_size_map: 0.3 # bigger voxel size

    publish:
      path_en:  true
      scan_publish_en:  true       # false: close all the point cloud output
      dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
      scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

    pcd_save:
      pcd_save_en: true
      interval: -1                 # how many LiDAR frames saved in each pcd file;
                                   # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
